### ISSUE TITLE
virtualenvwrapper plugin: activate only works on second cd

### ISSUE THREAD

**Issue by andreas-h** [robbyrussell/oh-my-zsh#2509]
I'm trying to use the virtuelenvwrapper plugin. I'm running into the situation that the first time I `cd` into a virtualenv, I get the error

    ∞ ➜  ~  cd Code/geodas 
    prepending /home2/hilboll/.virtualenvs/geodas-dev/bin to PATH
    discarding /home2/hilboll/.virtualenvs/geodas-dev/bin from PATH
    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/home2/hilboll/.local/lib/python2.7/site-packages/virtualenvwrapper/hook_loader.py", line 8, in <module>
        import inspect
      File "/usr/lib/python2.7/inspect.py", line 35, in <module>
        import string
      File "/usr/lib/python2.7/string.py", line 83, in <module>
        import re as _re
      File "/home2/hilboll/.virtualenvs/geodas-dev/lib/python2.7/re.py", line 105, in <module>
        import sre_compile
      File "/home2/hilboll/.virtualenvs/geodas-dev/lib/python2.7/sre_compile.py", line 14, in <module>
        import sre_parse
      File "/home2/hilboll/.virtualenvs/geodas-dev/lib/python2.7/sre_parse.py", line 17, in <module>
        from sre_constants import *
      File "/home2/hilboll/.virtualenvs/geodas-dev/lib/python2.7/sre_constants.py", line 18, in <module>
        from _sre import MAXREPEAT
    ImportError: cannot import name MAXREPEAT
    virtualenvwrapper.sh: There was a problem running the initialization hooks. 
    
    If Python could not import the module virtualenvwrapper.hook_loader,
    check that virtualenv has been installed for
    VIRTUALENVWRAPPER_PYTHON=/home2/hilboll/.virtualenvs/geodas-dev/bin/python and that PATH is
    set properly.
    ERROR: Environment '/home2/hilboll/.virtualenvs/geodas-dev' does not exist. Create it with 'mkvirtualenv /home2/hilboll/.virtualenvs/geodas-dev'.

However, when I then do `cd .. && cd my_directory`, everything works as expected (no errors).  Any idea what might be going on?

**Comment by mcornella** [comment]
It seems the workon function crashed and got you into [this error you see in line 243](https://bitbucket.org/dhellmann/virtualenvwrapper/src/9c702672f47cb72f84a1471c3e46ad80286230ed/virtualenvwrapper.sh?at=master#cl-243). It's a matter of following the execution trail upwards to see what might be the cause. It seems there is a bit of explanation in this issue: [virtualenvwrapper#40](https://bitbucket.org/dhellmann/virtualenvwrapper/issue/40/)

If this is still happening let me know and I'll see what I can do to help you.

**Comment by mcornella** [comment]
Any update on this issue?

**Comment by andreas-h** [comment]
Thanks, @mcornella, and sorry for the belated reply.  I switched machines in the meantime and the problem has somehow gone away ...
