### ISSUE TITLE
tmux plugin autocompletion produces segfault

### ISSUE THREAD

**Issue by aflavio** [robbyrussell/oh-my-zsh#5862]
I'm getting a segfault when try to use the first tab completing using the tmux plugin. 

The segfault is so similar with the issue [#2044](https://github.com/robbyrussell/oh-my-zsh/issues/2044) but It's for taskwarrior plugin and it has been fixed [zsh-users/zsh@844e569](https://github.com/zsh-users/zsh/commit/844e569b632fc032576edc039f793be47fde724e). 

This only happens on urxvt. I already tested it on xfce4-terminal and terminator and works well. 

urxvt: 9.22
zsh: zsh 5.3.1 (x86_64-unknown-linux-gnu)
tmux: 2.3
distro: archlinux

Some clue ?

**Comment by aflavio** [comment]
forgot about it. 


It's a urxvt bug using tmux. I just figured it out. 


```
GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from urxvt...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/urxvt -e .builds/vim/src/vim
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000000000041cf44 in rxvt_term::scr_refresh() ()
(gdb) bt
#0  0x000000000041cf44 in rxvt_term::scr_refresh() ()
#1  0x000000000041ea22 in rxvt_term::flush() ()
#2  0x0000000000439bce in ev_invoke_pending() ()
#3  0x000000000043a61d in ev_run ()
#4  0x00000000004192e3 in main ()
(gdb)
```
