### ISSUE TITLE
When I try to cd to directory with zsh I get an python error

### ISSUE THREAD

**Issue by unix2dos** [robbyrussell/oh-my-zsh#7850]
```
$ cd
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'


$ zsh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

zsh `cd`  get this error, other commands is good.  in bash `cd` is good.

**Comment by unix2dos** [comment]
i use   `rishabhsrao/iterm-tab-colors` change the tab color

in my .zshrc has `zgen load tysonwolker/iterm-tab-colors`

it has a python error
